# Generated by Django 5.0.1 on 2024-01-28 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UFC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='fighter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UFC.fighter'),
        ),
    ]
