# Generated by Django 5.0.1 on 2024-01-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UFC', '0002_alter_comment_fighter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mark',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
