# Generated by Django 5.0.1 on 2024-01-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UFC', '0003_alter_comment_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightningstyle',
            name='fight_style',
            field=models.ManyToManyField(blank=True, choices=[('Kickboxing', 'Kickboxing'), ('Muay Thai', 'Muay Thai'), ('Boxing', 'Boxing'), ('Jiu-Jitsu', 'Jiu-Jitsu'), ('Wrestling', 'Wrestling')], null=True, related_name='fighting_styles', to='UFC.fighter'),
        ),
    ]
