# Generated by Django 5.0.1 on 2024-01-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UFC', '0004_fightningstyle_fight_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_style', models.CharField(choices=[('Kickboxing', 'Kickboxing'), ('Muay Thai', 'Muay Thai'), ('Boxing', 'Boxing'), ('Jiu-Jitsu', 'Jiu-Jitsu'), ('Wrestling', 'Wrestling')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='fighter',
            name='fighting_styles',
            field=models.ManyToManyField(blank=True, related_name='fighters', to='UFC.fightingstyle'),
        ),
        migrations.DeleteModel(
            name='FightningStyle',
        ),
    ]
