# Generated by Django 5.0.1 on 2024-01-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UFC', '0005_fightingstyle_fighter_fighting_styles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightingstyle',
            name='fight_style',
            field=models.CharField(choices=[('Kickboxing', 'Kickboxing'), ('Muay Thai', 'Muay Thai'), ('Boxing', 'Boxing'), ('Jiu-Jitsu', 'Jiu-Jitsu'), ('Wrestling', 'Wrestling')], max_length=50, unique=True),
        ),
    ]
